<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>preview</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="System.Memory" Version="4.6.3" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Regex\Regex\Regex.csproj" />
    </ItemGroup>

    <Import Project="..\Shared\Shared.projitems" Label="Shared" />

</Project>
