name: InstallGraphviz

runs:
  using: "composite"
  steps:
    - name: Install Graphviz on Windows
      if: runner.os == 'Windows'
      run: |
          choco install graphviz -y
          echo "C:\Program Files\Graphviz\bin" | Out-File -FilePath $env:GITHUB_PATH -Append
      shell: bash

    - name: Install Graphviz on Linux
      if: runner.os == 'Linux'
      run: |
          sudo apt-get install graphviz
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      shell: bash

    - name: Install Graphviz on macOS
      if: runner.os == 'macOS'
      run: |
          brew install graphviz
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      shell: bash

    - name: SelfTest run dot
      run: |
          dot -V
      shell: bash      
