<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>preview</LangVersion>
        <RootNamespace>CSharpGrammar</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\ExtensibleParser\ExtensibleParser.csproj" />
        <ProjectReference Include="..\..\CsNitra\CsNitraGrammar\CsNitraGrammar.csproj" />
        <ProjectReference Include="..\..\..\Regex\Regex\Regex.csproj" OutputItemType="Analyzer" />
        <ProjectReference Include="..\..\..\TerminalGenerator\TerminalGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Cs1.grammar" />
        <EmbeddedResource Include="Cs2.grammar" />
        <EmbeddedResource Include="Cs3.grammar" />
        <EmbeddedResource Include="Cs4.grammar" />
        <EmbeddedResource Include="Cs5.grammar" />
        <EmbeddedResource Include="Cs6.grammar" />
        <EmbeddedResource Include="Cs7.grammar" />
        <EmbeddedResource Include="Cs8.grammar" />
        <EmbeddedResource Include="Cs9.grammar" />
        <EmbeddedResource Include="Cs10.grammar" />
        <EmbeddedResource Include="Cs11.grammar" />
        <EmbeddedResource Include="Cs12.grammar" />
        <EmbeddedResource Include="Cs13.grammar" />
        <EmbeddedResource Include="Cs14.grammar" />
    </ItemGroup>

    <Import Project="..\..\..\Shared\Shared.projitems" Label="Shared" />

</Project>
